#!/bin/bash
#SBATCH --job-name=ace
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -t 0-48:00
#SBATCH -p rtx8000
#SBATCH --mem=200000
#SBATCH -o ./ace5.o
#SBATCH -e ./ace5.e
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=8
#SBATCH --mail-user=318112194@qq.com
#SBATCH --gres=gpu:1

cd /scratch/zt2080/shizhe/eres/mrc
python trainer.py
    --data_dir=datasets/ace05\
    --task_name=ace05\
    --percent=5\
    --device=0\
